import type { Metadata } from 'next'
import BottomBar from '../../components/BottomBar'

export const metadata: Metadata = {
  title: 'Instapp',
  description: 'Generated by create next app',
}

export default function GeneralLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='h-screen'>
      {children}
      <BottomBar />
    </div>
  )
}
