import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TopBar from '../../components/TopBar'
import BottomBar from '../../components/BottomBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Instapp',
  description: 'Generated by create next app',
}

export default function GeneralLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='flex h-screen flex-col justify-between'>
      <TopBar />
      <div className='overflow-auto w-screen'>
        {children}
      </div>
      <BottomBar />
    </div>
  )
}
